// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package builder

import (
	"github.com/arabian9ts/sweeTest/app/domain/repository"
	"github.com/arabian9ts/sweeTest/app/interface/database"
	"github.com/arabian9ts/sweeTest/infrastructure"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeUserRepository() (repository.UserRepository, error) {
	sqlHandler := infrastructure.NewSqlHandler()
	userRepository, err := database.NewUserRepository(sqlHandler)
	if err != nil {
		return nil, err
	}
	return userRepository, nil
}

// wire.go:

var providerSet = wire.NewSet(infrastructure.NewSqlHandler, database.NewUserRepository)
