// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package builder

import (
	"github.com/arabian9ts/sweeTest/app/interface/controllers"
	"github.com/arabian9ts/sweeTest/app/interface/database"
	"github.com/arabian9ts/sweeTest/app/interface/handler"
	"github.com/arabian9ts/sweeTest/app/interface/presenter"
	"github.com/arabian9ts/sweeTest/app/usecase/interactor"
	"github.com/arabian9ts/sweeTest/app/usecase/repository"
	"github.com/arabian9ts/sweeTest/app/validator"
	"github.com/arabian9ts/sweeTest/infrastructure"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeUserRepository() (repository.UserRepository, error) {
	sqlHandler := infrastructure.NewSqlHandler()
	userRepository, err := database.NewUserRepository(sqlHandler)
	if err != nil {
		return nil, err
	}
	return userRepository, nil
}

func InitializeLectureRepository() (repository.LectureRepository, error) {
	sqlHandler := infrastructure.NewSqlHandler()
	lectureRepository, err := database.NewLectureRepository(sqlHandler)
	if err != nil {
		return nil, err
	}
	return lectureRepository, nil
}

func InitializeRootController() (*controllers.RootController, error) {
	sqlHandler := infrastructure.NewSqlHandler()
	userRepository, err := database.NewUserRepository(sqlHandler)
	if err != nil {
		return nil, err
	}
	userOutput := presenter.NewUserPresenter()
	validation := validator.NewDefaultValidator()
	studentsController, err := controllers.NewStudentsController(userRepository, userOutput, validation)
	if err != nil {
		return nil, err
	}
	assistantsController, err := controllers.NewAssistantsController(userRepository, userOutput, validation)
	if err != nil {
		return nil, err
	}
	teachersController, err := controllers.NewTeachersController(userRepository, userOutput, validation)
	if err != nil {
		return nil, err
	}
	lectureRepository, err := database.NewLectureRepository(sqlHandler)
	if err != nil {
		return nil, err
	}
	lectureOutput := presenter.NewLecturePresenter()
	lecturesController, err := controllers.NewLecturesController(lectureRepository, lectureOutput, validation)
	if err != nil {
		return nil, err
	}
	taskRepository, err := database.NewTaskRepository(sqlHandler)
	if err != nil {
		return nil, err
	}
	taskOutput := presenter.NewTaskPresenter()
	tasksController, err := controllers.NewTasksController(taskRepository, taskOutput, validation)
	if err != nil {
		return nil, err
	}
	authOutput := presenter.NewAuthPresenter()
	loginController, err := controllers.NewLoginController(userRepository, authOutput, validation)
	if err != nil {
		return nil, err
	}
	helpOutput := presenter.NewHelpPresenter()
	helpRepository, err := database.NewHelpRepository(sqlHandler)
	if err != nil {
		return nil, err
	}
	helpsController, err := controllers.NewHelpsController(helpOutput, helpRepository, validation)
	if err != nil {
		return nil, err
	}
	commentOutput := presenter.NewCommentPresenter()
	commentRepository := database.NewCommentRepository(sqlHandler)
	commentsController, err := controllers.NewCommentsController(commentOutput, commentRepository, validation)
	if err != nil {
		return nil, err
	}
	participationRepository, err := database.NewParticipationRepository(sqlHandler)
	if err != nil {
		return nil, err
	}
	participationOutput := presenter.NewParticipationPresenter()
	participationController, err := controllers.NewParticipationController(participationRepository, participationOutput, validation)
	if err != nil {
		return nil, err
	}
	participatingLecturesController, err := controllers.NewParticipatingLecturesController(lectureRepository, lectureOutput, validation)
	if err != nil {
		return nil, err
	}
	participantsController, err := controllers.NewParticipantsController(userRepository, userOutput, validation)
	if err != nil {
		return nil, err
	}
	rootController, err := controllers.NewRootController(studentsController, assistantsController, teachersController, lecturesController, tasksController, loginController, helpsController, commentsController, participationController, participatingLecturesController, participantsController)
	if err != nil {
		return nil, err
	}
	return rootController, nil
}

func InitializeRootHandler() (*handler.RootHandler, error) {
	sqlHandler := infrastructure.NewSqlHandler()
	userRepository, err := database.NewUserRepository(sqlHandler)
	if err != nil {
		return nil, err
	}
	authHandler, err := handler.NewAuthHandler(userRepository)
	if err != nil {
		return nil, err
	}
	meHandler, err := handler.NewMeHandler(userRepository)
	if err != nil {
		return nil, err
	}
	aliveHandler, err := handler.NewAliveHandler()
	if err != nil {
		return nil, err
	}
	rootHandler, err := handler.NewRootHandler(authHandler, meHandler, aliveHandler)
	if err != nil {
		return nil, err
	}
	return rootHandler, nil
}

// wire.go:

var repositorySet = wire.NewSet(infrastructure.NewSqlHandler, database.NewUserRepository, database.NewLectureRepository)

var handlerSet = wire.NewSet(infrastructure.NewSqlHandler, database.NewUserRepository, handler.NewAuthHandler, handler.NewMeHandler, handler.NewRootHandler, handler.NewAliveHandler)

var controllerSet = wire.NewSet(infrastructure.NewSqlHandler, database.NewUserRepository, database.NewLectureRepository, database.NewTaskRepository, database.NewHelpRepository, database.NewCommentRepository, database.NewParticipationRepository, controllers.NewStudentsController, controllers.NewAssistantsController, controllers.NewTeachersController, controllers.NewLecturesController, controllers.NewRootController, controllers.NewTasksController, controllers.NewLoginController, controllers.NewHelpsController, controllers.NewCommentsController, controllers.NewParticipationController, controllers.NewParticipatingLecturesController, controllers.NewParticipantsController, interactor.NewUserInteractor, interactor.NewLectureInteractor, interactor.NewTaskInteractor, interactor.NewAuthInteractor, interactor.NewHelpInteractor, interactor.NewCommentInteractor, interactor.NewParticipationInteractor, presenter.NewUserPresenter, presenter.NewLecturePresenter, presenter.NewTaskPresenter, presenter.NewAuthPresenter, presenter.NewHelpPresenter, presenter.NewCommentPresenter, presenter.NewParticipationPresenter, validator.NewDefaultValidator)
