# example env settings
mysql:
  username: sweeta
  password: kaba8ki3TA6
  database: sweetest
  dialect: mysql
  host: localhost
  port: 3306
  
jwt:
  secret: secret key
  valid_minutes: 43200 # 60 * 24 * 30 * time.Minute => 1 month
  realm: jwt auth
