// Code generated by Wire. DO NOT EDIT.

//go:generate injector
//+build !wireinject

package config

import (
	"github.com/google/wire"
)

// Injectors from injector.go:

func initializeSettings() (*Settings, error) {
	rdbms, err := NewRDBMSSettings()
	if err != nil {
		return nil, err
	}
	configSettings, err := NewSettings(rdbms)
	if err != nil {
		return nil, err
	}
	return configSettings, nil
}

// injector.go:

var providerSet = wire.NewSet(
	NewSettings,
	NewRDBMSSettings,
)
